import '../models/contact_model.dart';
import '../models/note_model.dart';
import '../models/follow_up_model.dart';
import '../models/lead_model.dart';

/// Default Data
/// البيانات الافتراضية الكاملة من الموقع القديم
class DefaultData {
  /// Generate all sample contacts (22 contacts)
  static List<ContactModel> generateAllContacts() {
    final now = DateTime.now();
    return [
      ContactModel(
        id: '1',
        name: 'أحمد محمد',
        companyName: 'نقل بلس',
        expoId: 'SmartCard#2048',
        category: 'نقل',
        booth: 'B12',
        description: 'تطبيق نقل طلاب - حلول ذكية للنقل المدرسي. شركة رائدة في مجال النقل الذكي. تقدم خدمات نقل آمنة ومريحة للطلاب مع تتبع مباشر.',
        scannedAt: now.subtract(const Duration(hours: 2)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501111111',
        email: 'info@naqlplus.com',
        website: 'www.naqlplus.com',
        brochure: BrochureModel(
          title: 'حلول النقل الذكي للمدارس',
          description: 'نقدم حلول نقل متكاملة وآمنة للمدارس مع تتبع مباشر للطلاب وأولياء الأمور. نظام ذكي يوفر الأمان والراحة للجميع.',
          features: ['تتبع مباشر للطلاب', 'إشعارات فورية', 'تقارير يومية', 'دعم 24/7', 'تطبيق موبايل', 'نظام إدارة متكامل'],
          services: ['نقل مدرسي', 'رحلات تعليمية', 'نقل طوارئ', 'نقل موظفين'],
        ),
      ),
      ContactModel(
        id: '2',
        name: 'سارة علي',
        companyName: 'تقنيات التعليم',
        expoId: 'SmartCard#3056',
        category: 'تعليم',
        booth: 'A5',
        description: 'حلول تعليمية ذكية ومنصات تعليم إلكتروني. منصات تفاعلية للتعلم عن بُعد مع محتوى تعليمي متقدم.',
        scannedAt: now.subtract(const Duration(hours: 5)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966502222222',
        email: 'contact@edutech.com',
        website: 'www.edutech.com',
        brochure: BrochureModel(
          title: 'منصات التعليم الإلكتروني',
          description: 'حلول تعليمية متكاملة تجمع بين التقنية والتعليم لتحقيق أفضل النتائج. منصات تفاعلية تجعل التعلم أكثر متعة وفعالية.',
          features: ['فصول افتراضية', 'محتوى تفاعلي', 'تقييم تلقائي', 'تقارير شاملة', 'دعم متعدد اللغات', 'تكامل مع أنظمة المدارس'],
          services: ['منصات تعليمية', 'تدريب المعلمين', 'استشارات تعليمية', 'تطوير المحتوى'],
        ),
      ),
      ContactModel(
        id: '3',
        name: 'خالد سعيد',
        companyName: 'استثمارات المستقبل',
        expoId: 'SmartCard#4123',
        category: 'استثمار',
        booth: 'C8',
        description: 'شركة استثمارية متخصصة في قطاع التعليم والتقنية. تمويل المشاريع الناشئة والشركات التقنية.',
        scannedAt: now.subtract(const Duration(days: 1)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966503333333',
        email: 'invest@future.com',
        website: 'www.future-invest.com',
      ),
      ContactModel(
        id: '4',
        name: 'ليلى حسن',
        companyName: 'منصة التعلم الذكي',
        expoId: 'SmartCard#5200',
        category: 'تعليم',
        booth: 'D15',
        description: 'منصة تعليمية متكاملة مع AI. محتوى تعليمي تفاعلي للطلاب والمعلمين مع تحليلات ذكية.',
        scannedAt: now.subtract(const Duration(hours: 3)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966504444444',
        email: 'hello@smartlearn.com',
        website: 'www.smartlearn.com',
      ),
      ContactModel(
        id: '5',
        name: 'محمد العلي',
        companyName: 'حلول الأمن السيبراني',
        expoId: 'SmartCard#6100',
        category: 'تقنية',
        booth: 'E20',
        description: 'حلول أمنية متقدمة للمؤسسات التعليمية. حماية البيانات والأنظمة من التهديدات السيبرانية.',
        scannedAt: now.subtract(const Duration(hours: 4)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966505555555',
        email: 'security@cybersolutions.com',
        website: 'www.cybersolutions.com',
      ),
      // Add more contacts... (continuing with remaining 17 contacts)
      ContactModel(
        id: '6',
        name: 'فاطمة الزهراني',
        companyName: 'مكتبة رقمية',
        expoId: 'SmartCard#7200',
        category: 'تعليم',
        booth: 'F8',
        description: 'مكتبة رقمية شاملة للكتب والمصادر التعليمية. آلاف الكتب الإلكترونية والمصادر التعليمية.',
        scannedAt: now.subtract(const Duration(hours: 6)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966506666666',
        email: 'info@digitallib.com',
        website: 'www.digitallib.com',
      ),
      ContactModel(
        id: '7',
        name: 'عبدالله القحطاني',
        companyName: 'أنظمة إدارة المدارس',
        expoId: 'SmartCard#8300',
        category: 'تعليم',
        booth: 'G12',
        description: 'أنظمة متكاملة لإدارة المدارس والطلاب. إدارة الحضور والغياب والدرجات والأنشطة.',
        scannedAt: now.subtract(const Duration(hours: 1)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966507777777',
        email: 'contact@schoolsys.com',
        website: 'www.schoolsys.com',
      ),
      ContactModel(
        id: '8',
        name: 'نورا السالم',
        companyName: 'تطبيقات الواقع المعزز',
        expoId: 'SmartCard#9400',
        category: 'تقنية',
        booth: 'H5',
        description: 'تطبيقات تعليمية باستخدام الواقع المعزز. تجارب تعليمية تفاعلية ثلاثية الأبعاد.',
        scannedAt: now.subtract(const Duration(hours: 7)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966508888888',
        email: 'ar@edutech.com',
        website: 'www.aredutech.com',
      ),
      ContactModel(
        id: '9',
        name: 'يوسف المطيري',
        companyName: 'شبكات الاتصال التعليمية',
        expoId: 'SmartCard#1050',
        category: 'تقنية',
        booth: 'I15',
        description: 'حلول شبكات متقدمة للمؤسسات التعليمية. بنية تحتية قوية للاتصال والإنترنت.',
        scannedAt: now.subtract(const Duration(days: 2)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966509999999',
        email: 'networks@techsol.com',
        website: 'www.techsol.com',
      ),
      ContactModel(
        id: '10',
        name: 'ريم العتيبي',
        companyName: 'منصة التدريب المهني',
        expoId: 'SmartCard#1160',
        category: 'تعليم',
        booth: 'J8',
        description: 'منصة متخصصة في التدريب المهني والتطوير الوظيفي. دورات تدريبية معتمدة.',
        scannedAt: now.subtract(const Duration(hours: 8)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501010101',
        email: 'training@proplatform.com',
        website: 'www.proplatform.com',
      ),
      ContactModel(
        id: '11',
        name: 'عمر الدوسري',
        companyName: 'حلول التخزين السحابي',
        expoId: 'SmartCard#1270',
        category: 'تقنية',
        booth: 'K10',
        description: 'خدمات تخزين سحابي آمنة للمؤسسات التعليمية. نسخ احتياطي تلقائي وحماية البيانات.',
        scannedAt: now.subtract(const Duration(hours: 9)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501111111',
        email: 'cloud@storage.com',
        website: 'www.cloudstorage.com',
      ),
      ContactModel(
        id: '12',
        name: 'هند الشمري',
        companyName: 'أكاديمية البرمجة',
        expoId: 'SmartCard#1380',
        category: 'تعليم',
        booth: 'L5',
        description: 'دورات برمجة للأطفال والمراهقين. تعليم البرمجة بطريقة تفاعلية وممتعة.',
        scannedAt: now.subtract(const Duration(hours: 10)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501212121',
        email: 'info@codeacademy.com',
        website: 'www.codeacademy.com',
      ),
      ContactModel(
        id: '13',
        name: 'طارق الحربي',
        companyName: 'أنظمة الحضور الذكية',
        expoId: 'SmartCard#1490',
        category: 'تقنية',
        booth: 'M15',
        description: 'أنظمة حضور وغياب ذكية باستخدام البصمة والوجه. حلول متكاملة للمدارس.',
        scannedAt: now.subtract(const Duration(days: 3)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501313131',
        email: 'attendance@smart.com',
        website: 'www.smartattendance.com',
      ),
      ContactModel(
        id: '14',
        name: 'سلمى العلي',
        companyName: 'منصة الاختبارات الإلكترونية',
        expoId: 'SmartCard#1500',
        category: 'تعليم',
        booth: 'N8',
        description: 'منصة متكاملة لإجراء الاختبارات الإلكترونية. تصحيح تلقائي وتقارير فورية.',
        scannedAt: now.subtract(const Duration(hours: 11)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501414141',
        email: 'exams@platform.com',
        website: 'www.examplatform.com',
      ),
      ContactModel(
        id: '15',
        name: 'ماجد السعيد',
        companyName: 'روبوتات التعليم',
        expoId: 'SmartCard#1610',
        category: 'تقنية',
        booth: 'O12',
        description: 'روبوتات تعليمية تفاعلية للأطفال. برمجة وتعلم من خلال اللعب.',
        scannedAt: now.subtract(const Duration(hours: 12)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501515151',
        email: 'robots@edu.com',
        website: 'www.edurobots.com',
      ),
      ContactModel(
        id: '16',
        name: 'نورة المطيري',
        companyName: 'مختبرات العلوم الافتراضية',
        expoId: 'SmartCard#1720',
        category: 'تعليم',
        booth: 'P20',
        description: 'مختبرات علوم افتراضية ثلاثية الأبعاد. تجارب آمنة وتفاعلية للطلاب.',
        scannedAt: now.subtract(const Duration(days: 4)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501616161',
        email: 'labs@virtual.com',
        website: 'www.virtuallabs.com',
      ),
      ContactModel(
        id: '17',
        name: 'خالد الزهراني',
        companyName: 'أنظمة الإدارة المالية',
        expoId: 'SmartCard#1830',
        category: 'إدارة',
        booth: 'Q5',
        description: 'أنظمة إدارة مالية متكاملة للمدارس. إدارة الرسوم والمصروفات والرواتب.',
        scannedAt: now.subtract(const Duration(hours: 13)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501717171',
        email: 'finance@systems.com',
        website: 'www.financesys.com',
      ),
      ContactModel(
        id: '18',
        name: 'لينا العتيبي',
        companyName: 'تطبيقات الواقع الافتراضي',
        expoId: 'SmartCard#1940',
        category: 'تقنية',
        booth: 'R15',
        description: 'تطبيقات تعليمية باستخدام الواقع الافتراضي. رحلات تعليمية افتراضية.',
        scannedAt: now.subtract(const Duration(hours: 14)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501818181',
        email: 'vr@apps.com',
        website: 'www.vrapp.com',
      ),
      ContactModel(
        id: '19',
        name: 'فيصل القحطاني',
        companyName: 'أنظمة المكتبات الرقمية',
        expoId: 'SmartCard#2050',
        category: 'تعليم',
        booth: 'S8',
        description: 'أنظمة إدارة مكتبات رقمية متكاملة. فهرسة وبحث متقدم للكتب والمصادر.',
        scannedAt: now.subtract(const Duration(days: 5)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966501919191',
        email: 'library@digital.com',
        website: 'www.digitallibsys.com',
      ),
      ContactModel(
        id: '20',
        name: 'مها الدوسري',
        companyName: 'منصة التواصل التعليمي',
        expoId: 'SmartCard#2160',
        category: 'تعليم',
        booth: 'T12',
        description: 'منصة تواصل بين المدرسة والطلاب وأولياء الأمور. إشعارات ورسائل فورية.',
        scannedAt: now.subtract(const Duration(hours: 15)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966502020202',
        email: 'communication@edu.com',
        website: 'www.educomm.com',
      ),
      ContactModel(
        id: '21',
        name: 'بندر الشمري',
        companyName: 'حلول الطباعة والنسخ',
        expoId: 'SmartCard#2270',
        category: 'خدمات',
        booth: 'U5',
        description: 'خدمات طباعة ونسخ للمؤسسات التعليمية. حلول متكاملة للطباعة الرقمية.',
        scannedAt: now.subtract(const Duration(hours: 16)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966502121212',
        email: 'print@services.com',
        website: 'www.printservices.com',
      ),
      ContactModel(
        id: '22',
        name: 'سارة المطيري',
        companyName: 'استشارات تعليمية',
        expoId: 'SmartCard#2380',
        category: 'استشارات',
        booth: 'V20',
        description: 'خدمات استشارية متخصصة في تطوير المناهج والأنظمة التعليمية. خبرة 20+ سنة.',
        scannedAt: now.subtract(const Duration(days: 6)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        phone: '+966502222222',
        email: 'consulting@edu.com',
        website: 'www.educonsulting.com',
      ),
    ];
  }

  /// Generate all sample leads (25 leads)
  static List<LeadModel> generateAllLeads() {
    final now = DateTime.now();
    return [
      LeadModel(
        id: '1',
        visitorId: 'visitor-1',
        visitorName: 'محمد أحمد',
        visitorExpoId: 'SmartCard#1200',
        scannedAt: now.subtract(const Duration(hours: 2)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'interested',
        aiScore: 85,
        notes: 'مهتم جداً بتطبيق نقل الطلاب. طلب عرض توضيحي خلال أسبوع. لديه 50 مدرسة كعميل محتمل.',
        followUpDate: now.add(const Duration(days: 7)),
        visitorPhone: '+966501234567',
        visitorEmail: 'mohammed@example.com',
        createdAt: now.subtract(const Duration(hours: 2)),
      ),
      LeadModel(
        id: '2',
        visitorId: 'visitor-2',
        visitorName: 'فاطمة علي',
        visitorExpoId: 'SmartCard#1305',
        scannedAt: now.subtract(const Duration(hours: 5)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'follow-up',
        aiScore: 72,
        notes: 'مهتم بشراكة تنفيذية. مناقشة استخدام تطبيق سمستر. متابعة بعد أسبوعين.',
        followUpDate: now.add(const Duration(days: 14)),
        visitorPhone: '+966502345678',
        visitorEmail: 'fatima@example.com',
        createdAt: now.subtract(const Duration(hours: 5)),
      ),
      LeadModel(
        id: '3',
        visitorId: 'visitor-3',
        visitorName: 'عبدالله السعيد',
        visitorExpoId: 'SmartCard#1400',
        scannedAt: now.subtract(const Duration(hours: 8)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'new',
        aiScore: 65,
        notes: 'زائر جديد مهتم بالتقنيات التعليمية. طلب معلومات إضافية.',
        followUpDate: now.add(const Duration(days: 5)),
        visitorPhone: '+966503456789',
        visitorEmail: 'abdullah@example.com',
        createdAt: now.subtract(const Duration(hours: 8)),
      ),
      LeadModel(
        id: '4',
        visitorId: 'visitor-4',
        visitorName: 'نورا العلي',
        visitorExpoId: 'SmartCard#1500',
        scannedAt: now.subtract(const Duration(hours: 12)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'contacted',
        aiScore: 78,
        notes: 'تم التواصل معها. مهتمة بمنصات التعليم الإلكتروني. متابعة بعد 3 أيام.',
        followUpDate: now.add(const Duration(days: 3)),
        visitorPhone: '+966504567890',
        visitorEmail: 'nora@example.com',
        createdAt: now.subtract(const Duration(hours: 12)),
      ),
      LeadModel(
        id: '5',
        visitorId: 'visitor-5',
        visitorName: 'يوسف الحربي',
        visitorExpoId: 'SmartCard#1600',
        scannedAt: now.subtract(const Duration(days: 1)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'interested',
        aiScore: 90,
        notes: 'عميل محتمل عالي الجودة. لديه 100+ مدرسة. طلب عرض شامل.',
        followUpDate: now.add(const Duration(days: 10)),
        visitorPhone: '+966505678901',
        visitorEmail: 'youssef@example.com',
        createdAt: now.subtract(const Duration(days: 1)),
      ),
      LeadModel(
        id: '6',
        visitorId: 'visitor-6',
        visitorName: 'ريم الدوسري',
        visitorExpoId: 'SmartCard#1700',
        scannedAt: now.subtract(const Duration(hours: 18)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'follow-up',
        aiScore: 70,
        notes: 'متابعة عرض الأسعار. تنتظر رد من الإدارة.',
        followUpDate: now.add(const Duration(days: 7)),
        visitorPhone: '+966506789012',
        visitorEmail: 'reem@example.com',
        createdAt: now.subtract(const Duration(hours: 18)),
      ),
      LeadModel(
        id: '7',
        visitorId: 'visitor-7',
        visitorName: 'خالد الزهراني',
        visitorExpoId: 'SmartCard#1800',
        scannedAt: now.subtract(const Duration(days: 2)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'new',
        aiScore: 55,
        notes: 'زائر جديد. يحتاج مزيد من المعلومات.',
        followUpDate: now.add(const Duration(days: 14)),
        visitorPhone: '+966507890123',
        visitorEmail: 'khalid@example.com',
        createdAt: now.subtract(const Duration(days: 2)),
      ),
      LeadModel(
        id: '8',
        visitorId: 'visitor-8',
        visitorName: 'لينا العتيبي',
        visitorExpoId: 'SmartCard#1900',
        scannedAt: now.subtract(const Duration(hours: 20)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'contacted',
        aiScore: 82,
        notes: 'تم التواصل. مهتمة جداً. طلبت عرض توضيحي.',
        followUpDate: now.add(const Duration(days: 4)),
        visitorPhone: '+966508901234',
        visitorEmail: 'lina@example.com',
        createdAt: now.subtract(const Duration(hours: 20)),
      ),
      LeadModel(
        id: '9',
        visitorId: 'visitor-9',
        visitorName: 'فيصل القحطاني',
        visitorExpoId: 'SmartCard#2000',
        scannedAt: now.subtract(const Duration(hours: 24)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'interested',
        aiScore: 88,
        notes: 'عميل محتمل ممتاز. لديه شبكة واسعة من المدارس.',
        followUpDate: now.add(const Duration(days: 6)),
        visitorPhone: '+966509012345',
        visitorEmail: 'faisal@example.com',
        createdAt: now.subtract(const Duration(hours: 24)),
      ),
      LeadModel(
        id: '10',
        visitorId: 'visitor-10',
        visitorName: 'مها الشمري',
        visitorExpoId: 'SmartCard#2100',
        scannedAt: now.subtract(const Duration(days: 3)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'not-interested',
        aiScore: 40,
        notes: 'غير مهتمة حالياً. قد تعود لاحقاً.',
        followUpDate: now.add(const Duration(days: 30)),
        visitorPhone: '+966500123456',
        visitorEmail: 'maha@example.com',
        createdAt: now.subtract(const Duration(days: 3)),
      ),
      LeadModel(
        id: '11',
        visitorId: 'visitor-11',
        visitorName: 'بندر المطيري',
        visitorExpoId: 'SmartCard#2200',
        scannedAt: now.subtract(const Duration(hours: 6)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'new',
        aiScore: 60,
        notes: 'زائر جديد. يحتاج شرح أكثر.',
        followUpDate: now.add(const Duration(days: 7)),
        visitorPhone: '+966501234567',
        visitorEmail: 'bandar@example.com',
        createdAt: now.subtract(const Duration(hours: 6)),
      ),
      LeadModel(
        id: '12',
        visitorId: 'visitor-12',
        visitorName: 'سارة الدوسري',
        visitorExpoId: 'SmartCard#2300',
        scannedAt: now.subtract(const Duration(hours: 10)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'contacted',
        aiScore: 75,
        notes: 'تم التواصل. تنتظر الرد على استفساراتها.',
        followUpDate: now.add(const Duration(days: 5)),
        visitorPhone: '+966502345678',
        visitorEmail: 'sara@example.com',
        createdAt: now.subtract(const Duration(hours: 10)),
      ),
      LeadModel(
        id: '13',
        visitorId: 'visitor-13',
        visitorName: 'طارق العلي',
        visitorExpoId: 'SmartCard#2400',
        scannedAt: now.subtract(const Duration(days: 4)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'interested',
        aiScore: 85,
        notes: 'مهتم جداً. طلب عرض شامل للمنتجات.',
        followUpDate: now.add(const Duration(days: 8)),
        visitorPhone: '+966503456789',
        visitorEmail: 'tariq@example.com',
        createdAt: now.subtract(const Duration(days: 4)),
      ),
      LeadModel(
        id: '14',
        visitorId: 'visitor-14',
        visitorName: 'هند الزهراني',
        visitorExpoId: 'SmartCard#2500',
        scannedAt: now.subtract(const Duration(hours: 14)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'follow-up',
        aiScore: 68,
        notes: 'متابعة عرض الأسعار. تنتظر موافقة الإدارة.',
        followUpDate: now.add(const Duration(days: 10)),
        visitorPhone: '+966504567890',
        visitorEmail: 'hind@example.com',
        createdAt: now.subtract(const Duration(hours: 14)),
      ),
      LeadModel(
        id: '15',
        visitorId: 'visitor-15',
        visitorName: 'عمر العتيبي',
        visitorExpoId: 'SmartCard#2600',
        scannedAt: now.subtract(const Duration(hours: 22)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'new',
        aiScore: 58,
        notes: 'زائر جديد. يحتاج معلومات أساسية.',
        followUpDate: now.add(const Duration(days: 12)),
        visitorPhone: '+966505678901',
        visitorEmail: 'omar@example.com',
        createdAt: now.subtract(const Duration(hours: 22)),
      ),
      LeadModel(
        id: '16',
        visitorId: 'visitor-16',
        visitorName: 'ليلى القحطاني',
        visitorExpoId: 'SmartCard#2700',
        scannedAt: now.subtract(const Duration(days: 5)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'contacted',
        aiScore: 80,
        notes: 'تم التواصل. مهتمة بشراكة طويلة الأمد.',
        followUpDate: now.add(const Duration(days: 6)),
        visitorPhone: '+966506789012',
        visitorEmail: 'layla@example.com',
        createdAt: now.subtract(const Duration(days: 5)),
      ),
      LeadModel(
        id: '17',
        visitorId: 'visitor-17',
        visitorName: 'ماجد الشمري',
        visitorExpoId: 'SmartCard#2800',
        scannedAt: now.subtract(const Duration(hours: 16)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'interested',
        aiScore: 92,
        notes: 'عميل محتمل ممتاز. لديه 200+ مدرسة. أولوية عالية.',
        followUpDate: now.add(const Duration(days: 3)),
        visitorPhone: '+966507890123',
        visitorEmail: 'majed@example.com',
        createdAt: now.subtract(const Duration(hours: 16)),
      ),
      LeadModel(
        id: '18',
        visitorId: 'visitor-18',
        visitorName: 'نورة المطيري',
        visitorExpoId: 'SmartCard#2900',
        scannedAt: now.subtract(const Duration(hours: 4)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'new',
        aiScore: 62,
        notes: 'زائر جديد. يحتاج شرح تفصيلي.',
        followUpDate: now.add(const Duration(days: 9)),
        visitorPhone: '+966508901234',
        visitorEmail: 'nora2@example.com',
        createdAt: now.subtract(const Duration(hours: 4)),
      ),
      LeadModel(
        id: '19',
        visitorId: 'visitor-19',
        visitorName: 'عبدالله الدوسري',
        visitorExpoId: 'SmartCard#3000',
        scannedAt: now.subtract(const Duration(days: 6)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'follow-up',
        aiScore: 73,
        notes: 'متابعة عرض توضيحي. تنتظر الموافقة.',
        followUpDate: now.add(const Duration(days: 11)),
        visitorPhone: '+966509012345',
        visitorEmail: 'abdullah2@example.com',
        createdAt: now.subtract(const Duration(days: 6)),
      ),
      LeadModel(
        id: '20',
        visitorId: 'visitor-20',
        visitorName: 'سلمى العلي',
        visitorExpoId: 'SmartCard#3100',
        scannedAt: now.subtract(const Duration(hours: 8)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'contacted',
        aiScore: 77,
        notes: 'تم التواصل. مهتمة بالمنتجات التعليمية.',
        followUpDate: now.add(const Duration(days: 4)),
        visitorPhone: '+966500123456',
        visitorEmail: 'salma@example.com',
        createdAt: now.subtract(const Duration(hours: 8)),
      ),
      LeadModel(
        id: '21',
        visitorId: 'visitor-21',
        visitorName: 'يوسف الزهراني',
        visitorExpoId: 'SmartCard#3200',
        scannedAt: now.subtract(const Duration(hours: 26)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'interested',
        aiScore: 87,
        notes: 'مهتم جداً. طلب عرض شامل مع عروض خاصة.',
        followUpDate: now.add(const Duration(days: 7)),
        visitorPhone: '+966501234567',
        visitorEmail: 'youssef2@example.com',
        createdAt: now.subtract(const Duration(hours: 26)),
      ),
      LeadModel(
        id: '22',
        visitorId: 'visitor-22',
        visitorName: 'ريم العتيبي',
        visitorExpoId: 'SmartCard#3300',
        scannedAt: now.subtract(const Duration(days: 7)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'new',
        aiScore: 56,
        notes: 'زائر جديد. يحتاج معلومات أساسية.',
        followUpDate: now.add(const Duration(days: 15)),
        visitorPhone: '+966502345678',
        visitorEmail: 'reem2@example.com',
        createdAt: now.subtract(const Duration(days: 7)),
      ),
      LeadModel(
        id: '23',
        visitorId: 'visitor-23',
        visitorName: 'خالد القحطاني',
        visitorExpoId: 'SmartCard#3400',
        scannedAt: now.subtract(const Duration(hours: 30)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'contacted',
        aiScore: 79,
        notes: 'تم التواصل. مهتم بالحلول التقنية.',
        followUpDate: now.add(const Duration(days: 5)),
        visitorPhone: '+966503456789',
        visitorEmail: 'khalid2@example.com',
        createdAt: now.subtract(const Duration(hours: 30)),
      ),
      LeadModel(
        id: '24',
        visitorId: 'visitor-24',
        visitorName: 'لينا الشمري',
        visitorExpoId: 'SmartCard#3500',
        scannedAt: now.subtract(const Duration(hours: 28)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'interested',
        aiScore: 83,
        notes: 'مهتمة جداً. طلبت عرض توضيحي شامل.',
        followUpDate: now.add(const Duration(days: 6)),
        visitorPhone: '+966504567890',
        visitorEmail: 'lina2@example.com',
        createdAt: now.subtract(const Duration(hours: 28)),
      ),
      LeadModel(
        id: '25',
        visitorId: 'visitor-25',
        visitorName: 'فيصل المطيري',
        visitorExpoId: 'SmartCard#3600',
        scannedAt: now.subtract(const Duration(days: 8)),
        eventId: 'event1',
        eventName: 'معرض التعليم 2024',
        status: 'follow-up',
        aiScore: 71,
        notes: 'متابعة عرض الأسعار. تنتظر الرد.',
        followUpDate: now.add(const Duration(days: 9)),
        visitorPhone: '+966505678901',
        visitorEmail: 'faisal2@example.com',
        createdAt: now.subtract(const Duration(days: 8)),
      ),
    ];
  }

  /// Generate all sample notes
  static List<NoteModel> generateAllNotes() {
    final now = DateTime.now();
    return [
      NoteModel(
        id: '1',
        contactId: '1',
        contactName: 'نقل بلس',
        contactExpoId: 'SmartCard#2048',
        content: 'مناقشة استخدام تطبيق سمستر. مهتم بشراكة تنفيذية. طلب عرض توضيحي. متابعة بعد أسبوعين. الشركة لديها 500+ مدرسة كعميل.',
        createdAt: now.subtract(const Duration(hours: 2)),
      ),
      NoteModel(
        id: '2',
        contactId: '2',
        contactName: 'تقنيات التعليم',
        contactExpoId: 'SmartCard#3056',
        content: 'عرض منصة تعليمية متقدمة. حلول تفاعلية للتعلم عن بُعد. طلب عرض توضيحي خلال أسبوع. إمكانية تخصيص المنصة حسب احتياجاتنا.',
        createdAt: now.subtract(const Duration(hours: 5)),
      ),
      NoteModel(
        id: '3',
        contactId: '3',
        contactName: 'استثمارات المستقبل',
        contactExpoId: 'SmartCard#4123',
        content: 'مناقشة فرص الاستثمار في قطاع التعليم. شركة كبيرة لديها رأس مال كبير.',
        createdAt: now.subtract(const Duration(hours: 8)),
      ),
      NoteModel(
        id: '4',
        contactId: '4',
        contactName: 'منصة التعلم الذكي',
        contactExpoId: 'SmartCard#5200',
        content: 'عرض منصة تعليمية مع AI. حلول متقدمة للتعلم الذكي.',
        createdAt: now.subtract(const Duration(hours: 3)),
      ),
      NoteModel(
        id: '5',
        contactId: '5',
        contactName: 'حلول الأمن السيبراني',
        contactExpoId: 'SmartCard#6100',
        content: 'مناقشة حلول الأمن للمدارس. مهم جداً لحماية البيانات.',
        createdAt: now.subtract(const Duration(hours: 4)),
      ),
      NoteModel(
        id: '6',
        contactId: '6',
        contactName: 'مكتبة رقمية',
        contactExpoId: 'SmartCard#7200',
        content: 'مكتبة رقمية شاملة. آلاف الكتب والمصادر التعليمية.',
        createdAt: now.subtract(const Duration(hours: 6)),
      ),
      NoteModel(
        id: '7',
        contactId: '7',
        contactName: 'أنظمة إدارة المدارس',
        contactExpoId: 'SmartCard#8300',
        content: 'أنظمة متكاملة لإدارة المدارس. حل شامل للإدارة.',
        createdAt: now.subtract(const Duration(hours: 1)),
      ),
      NoteModel(
        id: '8',
        contactId: '8',
        contactName: 'تطبيقات الواقع المعزز',
        contactExpoId: 'SmartCard#9400',
        content: 'تطبيقات AR للتعليم. تجارب تفاعلية ثلاثية الأبعاد.',
        createdAt: now.subtract(const Duration(hours: 7)),
      ),
      NoteModel(
        id: '9',
        contactId: '9',
        contactName: 'شبكات الاتصال التعليمية',
        contactExpoId: 'SmartCard#1050',
        content: 'حلول شبكات للمدارس. بنية تحتية قوية.',
        createdAt: now.subtract(const Duration(days: 2)),
      ),
      NoteModel(
        id: '10',
        contactId: '10',
        contactName: 'منصة التدريب المهني',
        contactExpoId: 'SmartCard#1160',
        content: 'منصة تدريب مهني. دورات معتمدة ومتخصصة.',
        createdAt: now.subtract(const Duration(hours: 8)),
      ),
      NoteModel(
        id: '11',
        contactId: '11',
        contactName: 'حلول التخزين السحابي',
        contactExpoId: 'SmartCard#1270',
        content: 'تخزين سحابي آمن. نسخ احتياطي تلقائي.',
        createdAt: now.subtract(const Duration(hours: 9)),
      ),
      NoteModel(
        id: '12',
        contactId: '12',
        contactName: 'أكاديمية البرمجة',
        contactExpoId: 'SmartCard#1380',
        content: 'دورات برمجة للأطفال. تعليم تفاعلي وممتع.',
        createdAt: now.subtract(const Duration(hours: 10)),
      ),
      NoteModel(
        id: '13',
        contactId: '13',
        contactName: 'أنظمة الحضور الذكية',
        contactExpoId: 'SmartCard#1490',
        content: 'أنظمة حضور ذكية. حلول متكاملة.',
        createdAt: now.subtract(const Duration(days: 3)),
      ),
      NoteModel(
        id: '14',
        contactId: '14',
        contactName: 'منصة الاختبارات الإلكترونية',
        contactExpoId: 'SmartCard#1500',
        content: 'منصة اختبارات إلكترونية. تصحيح تلقائي.',
        createdAt: now.subtract(const Duration(hours: 11)),
      ),
      NoteModel(
        id: '15',
        contactId: '15',
        contactName: 'روبوتات التعليم',
        contactExpoId: 'SmartCard#1610',
        content: 'روبوتات تعليمية. برمجة وتعلم من خلال اللعب.',
        createdAt: now.subtract(const Duration(hours: 12)),
      ),
    ];
  }

  /// Generate all sample follow-ups
  static List<FollowUpModel> generateAllFollowUps() {
    final now = DateTime.now();
    return [
      FollowUpModel(
        id: '1',
        contactId: '1',
        contactName: 'نقل بلس',
        contactExpoId: 'SmartCard#2048',
        followUpDate: now.add(const Duration(days: 7)),
        note: 'متابعة عرض الأسعار',
        isCompleted: false,
        createdAt: now.subtract(const Duration(days: 1)),
      ),
      FollowUpModel(
        id: '2',
        contactId: '2',
        contactName: 'تقنيات التعليم',
        contactExpoId: 'SmartCard#3056',
        followUpDate: now.add(const Duration(days: 3)),
        note: 'عرض توضيحي للمنصة',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 12)),
      ),
      FollowUpModel(
        id: '3',
        contactId: '3',
        contactName: 'استثمارات المستقبل',
        contactExpoId: 'SmartCard#4123',
        followUpDate: now.add(const Duration(days: 10)),
        note: 'متابعة فرص الاستثمار',
        isCompleted: false,
        createdAt: now.subtract(const Duration(days: 2)),
      ),
      FollowUpModel(
        id: '4',
        contactId: '4',
        contactName: 'منصة التعلم الذكي',
        contactExpoId: 'SmartCard#5200',
        followUpDate: now.add(const Duration(days: 5)),
        note: 'عرض توضيحي للمنصة',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 3)),
      ),
      FollowUpModel(
        id: '5',
        contactId: '5',
        contactName: 'حلول الأمن السيبراني',
        contactExpoId: 'SmartCard#6100',
        followUpDate: now.add(const Duration(days: 6)),
        note: 'مناقشة الحلول الأمنية',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 4)),
      ),
      FollowUpModel(
        id: '6',
        contactId: '6',
        contactName: 'مكتبة رقمية',
        contactExpoId: 'SmartCard#7200',
        followUpDate: now.add(const Duration(days: 4)),
        note: 'عرض المكتبة الرقمية',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 6)),
      ),
      FollowUpModel(
        id: '7',
        contactId: '7',
        contactName: 'أنظمة إدارة المدارس',
        contactExpoId: 'SmartCard#8300',
        followUpDate: now.add(const Duration(days: 8)),
        note: 'عرض الأنظمة',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 1)),
      ),
      FollowUpModel(
        id: '8',
        contactId: '8',
        contactName: 'تطبيقات الواقع المعزز',
        contactExpoId: 'SmartCard#9400',
        followUpDate: now.add(const Duration(days: 9)),
        note: 'تجربة التطبيقات',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 7)),
      ),
      FollowUpModel(
        id: '9',
        contactId: '9',
        contactName: 'شبكات الاتصال التعليمية',
        contactExpoId: 'SmartCard#1050',
        followUpDate: now.subtract(const Duration(days: 1)),
        note: 'مكالمة متابعة',
        isCompleted: true,
        completedAt: now.subtract(const Duration(hours: 2)),
        createdAt: now.subtract(const Duration(days: 2)),
      ),
      FollowUpModel(
        id: '10',
        contactId: '10',
        contactName: 'منصة التدريب المهني',
        contactExpoId: 'SmartCard#1160',
        followUpDate: now.add(const Duration(days: 11)),
        note: 'عرض المنصة',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 8)),
      ),
      FollowUpModel(
        id: '11',
        contactId: '11',
        contactName: 'حلول التخزين السحابي',
        contactExpoId: 'SmartCard#1270',
        followUpDate: now.add(const Duration(days: 12)),
        note: 'مناقشة الحلول',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 9)),
      ),
      FollowUpModel(
        id: '12',
        contactId: '12',
        contactName: 'أكاديمية البرمجة',
        contactExpoId: 'SmartCard#1380',
        followUpDate: now.add(const Duration(days: 13)),
        note: 'عرض الدورات',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 10)),
      ),
      FollowUpModel(
        id: '13',
        contactId: '13',
        contactName: 'أنظمة الحضور الذكية',
        contactExpoId: 'SmartCard#1490',
        followUpDate: now.add(const Duration(days: 14)),
        note: 'تجربة الأنظمة',
        isCompleted: false,
        createdAt: now.subtract(const Duration(days: 3)),
      ),
      FollowUpModel(
        id: '14',
        contactId: '14',
        contactName: 'منصة الاختبارات الإلكترونية',
        contactExpoId: 'SmartCard#1500',
        followUpDate: now.add(const Duration(days: 15)),
        note: 'عرض المنصة',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 11)),
      ),
      FollowUpModel(
        id: '15',
        contactId: '15',
        contactName: 'روبوتات التعليم',
        contactExpoId: 'SmartCard#1610',
        followUpDate: now.add(const Duration(days: 16)),
        note: 'تجربة الروبوتات',
        isCompleted: false,
        createdAt: now.subtract(const Duration(hours: 12)),
      ),
    ];
  }
}

